# Generated by Django 3.2.16 on 2026-06-17 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(choices=[('edu', 'Программирование'), ('theory', 'Теория'), ('quiz', 'Викторина')], max_length=16, verbose_name='Тип урока')),
                ('duration', models.PositiveSmallIntegerField(help_text='Укажите продолжительность курса в минутах.', verbose_name='Продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Отредактировано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
